apiVersion: v1
kind: Service
metadata:
  name: whatsapp-bot-service
  labels:
    app: whatsapp-bot
spec:
  ports:
  - port: 3000
    name: web
  clusterIP: None
  selector:
    app: whatsapp-bot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: whatsapp-bot # has to match .spec.template.metadata.labels
  serviceName: "whatsapp-bot-service"
  replicas: 1 # by default is 1
  minReadySeconds: 0 # by default is 0
  template:
    metadata:
      labels:
        app: whatsapp-bot # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: whatsapp-bot
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 3000
          name: whatsapp-bot-rest-api
        volumeMounts:
        - name: session-volume
          mountPath: /usr/src/app/.wwebjs_auth
  volumeClaimTemplates:
  - metadata:
      name: session-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi